// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmmuGsxEFNkFD_WLAvCWtbOz8A5F7sIGQ',
    appId: '1:186916298447:web:c45c4371e7bf56ed0661ba',
    messagingSenderId: '186916298447',
    projectId: 'authentication-of',
    authDomain: 'authentication-of.firebaseapp.com',
    storageBucket: 'authentication-of.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmw84ClgTzYfgTKBPnLLXERPGBE58TvFs',
    appId: '1:186916298447:android:969bbbf4b802bfa40661ba',
    messagingSenderId: '186916298447',
    projectId: 'authentication-of',
    storageBucket: 'authentication-of.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5a7XVO2nBKbMzjY0nybNnZ3q5aqmxwG8',
    appId: '1:186916298447:ios:8028c206fd8c3fb10661ba',
    messagingSenderId: '186916298447',
    projectId: 'authentication-of',
    storageBucket: 'authentication-of.appspot.com',
    iosBundleId: 'com.example.ALLS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5a7XVO2nBKbMzjY0nybNnZ3q5aqmxwG8',
    appId: '1:186916298447:ios:8028c206fd8c3fb10661ba',
    messagingSenderId: '186916298447',
    projectId: 'authentication-of',
    storageBucket: 'authentication-of.appspot.com',
    iosBundleId: 'com.example.ALLS',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmmuGsxEFNkFD_WLAvCWtbOz8A5F7sIGQ',
    appId: '1:186916298447:web:bd718c31a82daef20661ba',
    messagingSenderId: '186916298447',
    projectId: 'authentication-of',
    authDomain: 'authentication-of.firebaseapp.com',
    storageBucket: 'authentication-of.appspot.com',
  );

}